name: CI

on:
  push:
    branches:
      - trunk
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - name: Build with bun
        run: bun install && bun build
      - uses: actions/upload-pages-artifact@v4
        with:
          path: .vuepress/dist

  deploy:
    runs-on: ubuntu-slim
    if: github.ref == 'refs/heads/trunk' && github.event_name == 'push'
    needs: build
    environment:
      name: github-pages
    permissions:
      id-token: write
      pages: write
    steps:
      - uses: actions/deploy-pages@v4
